import { prisma } from "../../../../lib/prisma";
import { deleteInquiry, updateInquiryStatus } from "../../_actions/cms";
import { PageHeader } from "../../_components/PageHeader";
import { StatusBadge } from "../../_components/StatusBadge";

export default async function InquiriesPage() {
  const inquiries = await prisma.inquiry.findMany({ orderBy: { createdAt: "desc" } });
  return <><PageHeader title="采购询盘" description="跟进来自网站的箱包批发、贴牌生产与 OEM/ODM 定制需求。" /><div className="space-y-3">{inquiries.map((item) => <article className="rounded-md border border-[#e1e6ec] bg-white p-5" key={item.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><h2 className="font-bold">{item.name}</h2><StatusBadge status={item.status} /></div><p className="mt-1 text-xs text-slate-500">{item.email}{item.phone ? ` · ${item.phone}` : ""}{item.country ? ` · ${item.country}` : ""}</p><p className="mt-1 text-xs font-medium text-slate-700">{item.company || "未填写公司名称"}{item.product ? ` · 意向产品：${item.product}` : ""}</p></div><time className="text-xs text-slate-400">{item.createdAt.toLocaleString("zh-CN")}</time></div><p className="mt-4 whitespace-pre-wrap rounded bg-slate-50 p-4 text-sm leading-6 text-slate-700">{item.message}</p><div className="mt-4 flex items-center gap-4"><form className="flex items-center gap-2" action={updateInquiryStatus}><input type="hidden" name="id" value={item.id} /><select className="!w-40 !py-1.5 text-xs" name="status" defaultValue={item.status}><option value="NEW">新询盘</option><option value="IN_PROGRESS">跟进中</option><option value="CLOSED">已关闭</option></select><button className="text-xs font-semibold text-[#a55734]">更新状态</button></form><form action={deleteInquiry}><input type="hidden" name="id" value={item.id} /><button className="text-xs font-semibold text-red-700">删除</button></form></div></article>)}{inquiries.length === 0 ? <p className="rounded-md border border-[#e1e6ec] bg-white py-12 text-center text-sm text-slate-500">暂无采购询盘。</p> : null}</div></>;
}
